### ISSUE TITLE
bug: updateAvailability is 1 (UPDATE_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by RRGT19** [capawesome-team/capacitor-app-update#46]
**Plugin version:**
1.3.1

**Platform(s):**
- Android

**Current behavior:**
I'm not sure if this is a bug or a wrong implementation. I'm trying to test the app update using [Google Test in-app updates](https://developer.android.com/guide/playcore/in-app-updates/test).

I have uploaded a version with a higher versionCode and nothing happens, my implementation didn't fire the custom alert.

After, and just for testing purposes, I uploaded a new version to open an alert and see what is the AppInfo returning. The `updateAvailability` is 1 (UPDATE_NOT_AVAILABLE).

![](https://i.ibb.co/k9g90Rq/6a5364e5-04e9-4c30-a5fa-42cd0818baaa.jpg)

1. Notice how `updateAvailability` is 1.
2. Notice that `currentVersion` is higher than `availableVersion`. The `availableVersion` that shows the image (5100142) is very very old in my history, I don't know where and why that value was returned.

As a third attempt, I have uploaded a new version with a higher versionCode and versionName, and, same result as before. The `availableVersion` is still 5100142.

![](https://i.ibb.co/1fRsKPq/Screen-Shot-2022-07-03-at-10-33-30-PM.png)

I don't understand what is happening.

Also, the question that comes to my mind is:

- Should I rely on `appUpdateInfo.updateAvailability === AppUpdateAvailability.UPDATE_AVAILABLE` or I need to convert `currentVersion` and `availableVersion` to numbers and compare them?

**Example:**
```typescript
const current = +currentVersion;
const newest = +availableVersion;
const updateIsAvailable: boolean = newest > current;
```

- With my Android v12 test device, the immediate and flexible flows are both `false`. Why? Perhaps this flows are just available if the App is in production?

**Expected behavior:**
`updateAvailability` should be 2 if there is an update.

**Related code:**
This is my implementation:

```typescript
    AppUpdate.getAppUpdateInfo()
      .then(info => {
        if (info.updateAvailability === AppUpdateAvailability.UPDATE_AVAILABLE) {
          // There is an update available
        }
      });
  }
```

**Additional information:**
I don't know if this is a bug or something about Google Internal Testing thing.

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @RRGT19,
this looks like a duplicate of #18. Please have a look at this comment: https://github.com/capawesome-team/capacitor-app-update/issues/18#issuecomment-886706841

> Should I rely on appUpdateInfo.updateAvailability === AppUpdateAvailability.UPDATE_AVAILABLE

Yes, i recommend to use  `AppUpdateAvailability.UPDATE_AVAILABLE`.

**Comment by RRGT19** [comment]
@robingenz 
Thanks, the link you provided helped me a lot.

I had confused normal **Internal Testing** with **Internal app sharing**. The names are similar, but they are really different things.

Thanks again, I understand we can close this thread.
