### ISSUE TITLE
feat: Is there a way we can access the app version name

### ISSUE THREAD

**Issue by vkyeswa** [capawesome-team/capacitor-app-update#47]
Currently, the application gives us the version code say 14... is there a way we can get the name, like 5.0.3

**Comment by robingenz** [comment]
'getAppUpdateInfo(...)' should return the version name. Please share your plugin call result.

**Comment by aminBenSlimen** [comment]
it would be nice if there is an example of the function's return value, because trying to log the result is very hard since you it require deployment, etc... thanks.

**Comment by vkyeswa** [comment]
> 'getAppUpdateInfo(...)' should return the version name. Please share your plugin call result.

according to the documentation


availableVersion | string | Version code (Android) or CFBundleShortVersionString (iOS) of the update. Only available for Android and iOS.
-- | -- | --


it gives the Version Code but does not give the Version Name, I find that a name is more presentable to the user say **version 4.0.2** is available other than **version 16** where 16 is the build number(Android)

**Comment by robingenz** [comment]
Okay, got it now. The Android api unfortunately does not give me the version name of the update (see [here](https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo)). So I could only return the current version name. You can already fetch the current version **name** using https://capacitorjs.com/docs/apis/app#getinfo
So this information is already provided by a Capacitor core plugin.
