### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by nx-irvin** [capawesome-team/capacitor-app-update#54]
**Plugin version:**
v2.0.0

**Platform(s):**
Adroid

**Current behavior:**
After calling 'performImmediateUpdate ' or 'startFlexibleUpdate' and 'completeFlexibleUpdate ' the dialog to update the app is shown, the download and installation progress is shown but at the end nothing happens. The App remains without updating.

**Expected behavior:**
The app is updated to the latest version available on Google Play Store

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0
  @capacitor/ios: 4.4.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.4.0
  @capacitor/core: 4.4.0
  @capacitor/android: 4.4.0

[success] Android looking great! 👌```

**Comment by robingenz** [comment]
Hi @nx-irvin,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.
Please also provide a Screen-Recording of the current behavior.
