### ISSUE TITLE
feat: different url to show updates instantly

### ISSUE THREAD

**Issue by EinfachHans** [capawesome-team/capacitor-app-update#55]
**Is your feature request related to a problem? Please describe.**

The lookup url seems to be cached somehow when calling from swift code, so updates only shows nearly after 24 hourse of an update be-ing released.

**Describe the solution you'd like**

Check this post:https://developer.apple.com/forums/thread/97122?answerId=374946022#374946022

It's old, but when i manually tried it out he Option B URL instantly shows the update info, while Option A did not.

**Comment by robingenz** [comment]
You can already provide the country, but the URL will have a different format than in the linked post:
https://github.com/capawesome-team/capacitor-app-update/blob/f52ded5811af1dc861edaff8cf9f70aeed75ab31/ios/Plugin/AppUpdatePlugin.swift#L26

Have you tried passing the `country` parameter?

**Comment by robingenz** [comment]
I also found another good option: https://developer.apple.com/forums/thread/125461?answerId=721086022#721086022
I will provide you a dev build.

**Comment by robingenz** [comment]
@EinfachHans You can give it a try:

```
npm i @capawesome/capacitor-app-update@2.0.0-dev.91013b6.1667321556
```

**Comment by EinfachHans** [comment]
can't really verify, because we didn't have a fresh new release atm 🤔

**Comment by EinfachHans** [comment]
@robingenz We just released a new version so i was able to test - looks like your solution works 🎉

**Comment by robingenz** [comment]
@EinfachHans Great, thank you for testing!
