### ISSUE TITLE
feat: Obtain version name of an app that is live in the PlayStore

### ISSUE THREAD

**Issue by Harsha192** [capawesome-team/capacitor-app-update#57]
Hi, is it possible to obtain the version name of an android app that is live on the play store? Since the version code can be obtained using the attribute 'availableVersion' from AppUpdateInfo, I was wondering whether it's possible to get the version name. 

By the way by version name I mean the version that is displayed to the user, for example 22.1011.2

**Comment by robingenz** [comment]
Hi @Harsha192,
thank you for your request.
The version name is unfortunately not provided by Android, see docs: https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo.html

For this reason i am closing this issue.

**Comment by gkielwasser** [comment]
> Hi @Harsha192, thank you for your request. The version name is unfortunately not provided by Android, see docs: https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo.html
> 
> For this reason i am closing this issue.

Hi @robingenz,

It is true version name it is not available in `AppUpdateInfo` but could we retrieve it from `PackageInfo` ?

```
try {
    PackageInfo pInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), 0);
    String version = pInfo.versionName;
} catch (PackageManager.NameNotFoundException e) {
    e.printStackTrace();
}
```

Otherwise this package wouldn't be sufficient to fully handle app update management. For instance in Play Store the version name is displayed. Displaying the version code in the application would be pertubant and would not match with what is displayed in Play Store. Also in io platform it is the version name that is returned.

Thanks for feedback !

**Comment by robingenz** [comment]
@gkielwasser That's right. But we can only retrieve it for the current version, not the next/available version.
And my understanding was that the feature request referred to the next/available version (in Play Store).

**Comment by gkielwasser** [comment]
> @gkielwasser That's right. But we can only retrieve it for the current version, not the next/available version. And my understanding was that the feature request referred to the next/available version (in Play Store).

Your're completely right ! Also I have found your [comment](https://github.com/capawesome-team/capacitor-app-update/issues/47#issuecomment-1204861002) stating the current version name could just be read from capacitor.

Thanks a lot
