### ISSUE TITLE
bug: Fuzzy google error message on Android devices

### ISSUE THREAD

**Issue by AVillalonga** [capawesome-team/capacitor-app-update#59]
**Plugin version:**

- 2.0.1

**Platform(s) & Device(s):** 

- Android ( Emulator )

**Frameworks:**

- Ionic 6
- Capacitor 4 
- Angular 14

**Current behavior:**

I'm trying fetch app informations like the code bellow.

```Typescript
async onAppLaunch() {
  const appInfo = await AppUpdate.getAppUpdateInfo();
  
  const current = appInfo.currentVersion;
  const latest = appInfo.availableVersion;
}
```

`getAppUpdateInfo()` throwing me this (google) error:

```
Install Error(-6): The download/install is not allowed, due to the current device state (e.g. low battery, low disk space, ...). (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_INSTALL_NOT_ALLOWED)
```

After some research, my issue was fixed by using a device with google play and connecting an account to it, like explain [here (stackoverflow)](https://stackoverflow.com/a/67329600/14294128).

**Expected behavior:**

Check if the device is connected to google play and throw an understandable error message if not. Like this many young capacitor developers like me will save time ❤️ 

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.2.0
  @capacitor/android: 4.2.0
  @capacitor/core: 4.2.0
  @capacitor/ios: 4.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
@AVillalonga Thank you for your request and all the information!

Would you be willing to test my fix?

```
npm i @capawesome/capacitor-app-update@2.1.0-dev.9759507.1674335108
```
