### ISSUE TITLE
feat: Receive versionName instead/alongside versionCode on Android

### ISSUE THREAD

**Issue by swebSi** [capawesome-team/capacitor-app-update#67]
**Is your feature request related to a problem? Please describe.**
We are using semantic versioning of our app and we would like to use that to determine if we need to notify the user about a new version or to force update.
Currently on android it returns versionCode and no versionName.

getAppUpdateInfo() returns availableVersion as string on iOS (example: "2.5.2") and integer on [Android](https://developer.android.com/studio/publish/versioning#kts).  (example: 7475)

**Describe the solution you'd like**
I would like to receive availableVersion as versionName on android or at least have it as a separate available property 

**Describe alternatives you've considered**
We considered using versionCode but its a problem keeping track of updates between android / iOS. 

Thank you for your work & answers

**Comment by robingenz** [comment]
> I would like to receive availableVersion as versionName on android or at least have it as a separate available property

Unfortunately, this information is not provided by the Google Play SDK (see [here](https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo)). I only have access to the `VersionName` of the version currently installed on the device. 
For this reason i am closing this issue.
